### ISSUE TITLE
Image is not loading

### ISSUE THREAD

**Issue by nnagewad** [matheusgrieger/vue-clazy-load#10]
I've followed the instructions and although the i see the `loaded` class, no image is displayed.

**Comment by matheusgrieger** [comment]
Can you show me a sample of your code?

**Comment by nnagewad** [comment]
Sure can. I've setup a repo: https://github.com/nnagewad/personal_website/blob/master/src/components/About.vue

**Comment by matheusgrieger** [comment]
Thank you!
Now, let me see if I get it. Does the `<img>` tag exists on your DOM, with the `loaded` class?
If not, it may be related to #8. Otherwhise, there is something else going on. I've got some other personal issues to solve, and couldn't publish the new version with that fix yet, but it'll be up soon.

**Comment by matheusgrieger** [comment]
Same as issue #8. Will push a fix asap.

**Comment by matheusgrieger** [comment]
Solved on v0.4.1
