### ISSUE TITLE
updated to 0.4.1 Cannot read property 'install' of undefined

### ISSUE THREAD

**Issue by cannap** [matheusgrieger/vue-clazy-load#13]
Hi i try to use it via nuxt but since the update it does no longer work :/

**Comment by cannap** [comment]
```js
import clazyload from 'vue-clazy-load'
Vue.use(clazyload)

//nux config**/

```js
 plugins: [
    '~/plugins/font-awesome.js',
]
```

**Comment by matheusgrieger** [comment]
As soon as I published the new version I realized what I've done but couldn't fix it in time. My bad! :sweat_smile: 

I'll push a new version in a few minutes.

**Comment by matheusgrieger** [comment]
Please, test again. If the problem persists, let me know!
