### ISSUE TITLE
Emit 'load' with event parameter

### ISSUE THREAD

**Issue by dfector** [matheusgrieger/vue-clazy-load#15]
I love this component!  It's saved me a bunch of time.

Is the component's load event supposed to include the $event parameter?

I want to change the style of the component after the 'load' event fires (specifically, change the background image to the newly loaded img).  But I can't access the $event parameter in my handler.

```html
<clazy-load v-bind:src="item.thumbnail" v-on:load="myHandler(item.thumbnail)">
  <img :src="item.thumbnail" style="display:none"/>
  <div slot="placeholder">Loading...</div>
</clazy-load>
```

```javascript
function myHandler(thumbnail, event) {
    event.target.style.backgroundImage = 'url(' + thumbnail + ')';
}
```

I'm new to Vue, so it's entirely possible that I'm missing something obvious.

**Comment by matheusgrieger** [comment]
Hello and I'm glad Vue Clazy Load has been useful for you!

Well, for starters, when you want the `$event` parameter, you have to explicitly indicate it, like so:

```html
<clazy-load :src="item.thumbnail" @load="myHandler(item.thumbnail, $event)">
```

But currently Clazy Load does not send any data in the `load` event. For what you're trying to do, though, you can easily accomplish with Vue alone:

```html
<clazy-load :src="item.thumbnail" @load="myHandler(item)">
  <img :src="item.thumbnail" :style="{ display: 'none', backgroundImage: item.loaded && `url(${item.thumbnail})` }">
</clazy-load>
```

```js
methods: {
  myHandler(item) {
    item.loaded = true
  }
}
```

This way, whenever your item is loaded, the background will be added to the image automatically by Vue. You can check [Vue's style documentation](https://vuejs.org/v2/guide/class-and-style.html#Binding-Inline-Styles) for more details.

Hope this helps!
