### ISSUE TITLE
Example page doesn't show images in FireFox

### ISSUE THREAD

**Issue by Alexk12** [matheusgrieger/vue-clazy-load#3]
Example page works in Chrome 62.0.3202.94 64bit, but doesn't show images in FireFox 56.0.2 64bit and in IE 11.0.9600.17633. OS: Windows 7.

**Comment by matheusgrieger** [comment]
That seems to be some CSS issue. I'll be checking on that later, thanks for reporting!

The JavaScript and Vue are all good and working, btw :smiley:
