### ISSUE TITLE
Can't find variable: IntersectionObserver - Safari

### ISSUE THREAD

**Issue by pmochine** [matheusgrieger/vue-clazy-load#7]
So I really love the vue clazy load, but I just tried it on Safari and got an error on your website:

https://matheusgrieger.github.io/vue-clazy-load/example/index.html

[Vue warn]: Error in nextTick: "ReferenceError: Can't find variable: IntersectionObserver"

found in

---> ClazyLoad

**Comment by pmochine** [comment]
Oh didn't saw that with Polyfill!

**Comment by matheusgrieger** [comment]
Yes, if the browser doesn't support it, you need to add some polyfill. An example is given [in the docs](https://github.com/matheusgrieger/vue-clazy-load#scroll-watching-behavior).

If the problem persists, please, feel free to reopen this issue!
