### ISSUE TITLE
slot="image"

### ISSUE THREAD

**Issue by koslo** [matheusgrieger/vue-clazy-load#8]
Hi, 
example not working unless defining the image slot.
i use:
"vue": "^2.5.7",
"vue-material": "beta",

So adding the image slot to the first transition it works well.

**Comment by matheusgrieger** [comment]
Are you sure this bug really happens? You can see from the [example page](https://matheusgrieger.github.io/vue-clazy-load/example/index.html), that it works nicely without `slot="image"`. Can you check again, as I was not able to reproduce this bug?

**Comment by koslo** [comment]
Hi, 
via npm/yarn the newest version is 0.3.0.
i compared the github code from release 0.3 to the master code. The npm package is not update to date. 
On 0.3-code the use of `this.$slots.default` is missing in the render function. This causes the problem.
Can you push the newest version to npm?
Thx.

**Comment by matheusgrieger** [comment]
Really? That's odd. I'll soon publish it with some other minor improvements that I've been working on. Thanks for notifying me!

**Comment by koslo** [comment]
Great. Thanks for your work.
